name       : ffmpeg-chromium
version    : '66.0.3359.139'
release    : 1
source     :
    - https://commondatastorage.googleapis.com/chromium-browser-official/chromium-66.0.3359.139.tar.xz : be75a5b5f8c5789d359238f374a43bf52ded49425f13ed68b8021c24e2e264b2
license    :
    - BSD-3-Clause
    - LGPL-3.0-or-later
    - GPL-3.0-or-later
component  : multimedia.codecs
summary    : Chromium's ffmpeg for Chromium based browsers
description: |
    Chromium's ffmpeg for Chromium based browsers such as Opera and Vivaldi
clang      : yes
patterns   :
    - /usr/lib64/*
builddeps  :
    - pkgconfig(gtk+-x11-3.0)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(lcms2)
    - pkgconfig(libjpeg)
    - pkgconfig(libpci)
    - pkgconfig(libpulse)
    - pkgconfig(libxslt)
    - pkgconfig(nss)
    - pkgconfig(xtst)
    - pkgconfig(xscrnsaver)
    - cups-devel
    - git
setup      : |
    FLAGS=(`cat $pkgfiles/gn-build-config`)

    # Bootstrap GN with build config
    python tools/gn/bootstrap/bootstrap.py --gn-gen-args "${FLAGS[*]}" -v
build      : |
    ninja -C out/Release media/ffmpeg -v
install    : |
    install -Dm00644 out/Release/libffmpeg.so $installdir/%libdir%/libffmpeg.so
