name       : ffmpeg-chromium
version    : '68.0.3440.106'
release    : 3
source     :
    - https://commondatastorage.googleapis.com/chromium-browser-official/chromium-68.0.3440.106.tar.xz : 7021040635a0a0d47f699bdb22e3ef5c91482e4f51b428d1de3016da95f0e698
license    :
    - BSD-3-Clause
    - LGPL-3.0-or-later
    - GPL-3.0-or-later
component  : multimedia.codecs
summary    : Chromium's ffmpeg for Chromium based browsers
description: |
    Chromium's ffmpeg for Chromium based browsers such as Opera and Vivaldi with support for proprietary codecs such as H.264 enabled.
clang      : yes
patterns   :
    - /usr/lib64/*
builddeps  :
    - pkgconfig(gtk+-x11-3.0)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(lcms2)
    - pkgconfig(libjpeg)
    - pkgconfig(libpci)
    - pkgconfig(libpulse)
    - pkgconfig(libxslt)
    - pkgconfig(nss)
    - pkgconfig(xtst)
    - pkgconfig(xscrnsaver)
    - cups-devel
    - git
setup      : |
    %patch -p1 < $pkgfiles/0001-Use-ar.patch

    FLAGS=(`cat $pkgfiles/gn-build-config`)

    # Bootstrap GN with build config
    python tools/gn/bootstrap/bootstrap.py --gn-gen-args "${FLAGS[*]}" -v
build      : |
    ninja -C out/Release media/ffmpeg -v
install    : |
    install -Dm00644 out/Release/libffmpeg.so $installdir/%libdir%/libffmpeg.so
