name       : ffmpeg-chromium
version    : 69.0.3497.81
release    : 4
source     :
    - https://commondatastorage.googleapis.com/chromium-browser-official/chromium-69.0.3497.81.tar.xz : 165ac7d0d4588e6b4a16331e0a9906ed013f2d29a96b54f0ea78fa0298f97144
license    :
    - BSD-3-Clause
    - LGPL-3.0-or-later
    - GPL-3.0-or-later
component  : multimedia.codecs
summary    : Chromium's ffmpeg for Chromium based browsers
description: |
    Chromium's ffmpeg for Chromium based browsers such as Opera and Vivaldi with support for proprietary codecs such as H.264 enabled.
clang      : yes
libsplit   : no
builddeps  :
    - pkgconfig(gtk+-x11-3.0)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(lcms2)
    - pkgconfig(libjpeg)
    - pkgconfig(libpci)
    - pkgconfig(libpulse)
    - pkgconfig(libxslt)
    - pkgconfig(nss)
    - pkgconfig(xtst)
    - pkgconfig(xscrnsaver)
    - cups-devel
    - git
setup      : |
    unset LD_AS_NEEDED
    export AR=ar

    FLAGS=(`cat $pkgfiles/gn-build-config`)

    # Bootstrap GN with build config
    python tools/gn/bootstrap/bootstrap.py --gn-gen-args "${FLAGS[*]}"
build      : |
    unset LD_AS_NEEDED
    export AR=ar
    ninja -C out/Release media/ffmpeg -v
install    : |
    install -Dm00644 out/Release/libffmpeg.so $installdir/%libdir%/libffmpeg.so
