name       : ffmpeg-chromium
version    : 71.0.3578.98
release    : 5
source     :
    - https://commondatastorage.googleapis.com/chromium-browser-official/chromium-71.0.3578.98.tar.xz : 1c56a9e30825774c83d568d194e9585625c6e90f81ee0ef09760fcedc86b9d45
license    :
    - BSD-3-Clause
    - LGPL-3.0-or-later
    - GPL-3.0-or-later
component  : multimedia.codecs
summary    : Chromium's ffmpeg for Chromium based browsers
description: |
    Chromium's ffmpeg for Chromium based browsers such as Opera and Vivaldi with support for proprietary codecs such as H.264 enabled.
clang      : yes
libsplit   : no
builddeps  :
    - pkgconfig(gtk+-x11-3.0)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(lcms2)
    - pkgconfig(libjpeg)
    - pkgconfig(libpci)
    - pkgconfig(libpulse)
    - pkgconfig(libxslt)
    - pkgconfig(nss)
    - pkgconfig(xtst)
    - pkgconfig(xscrnsaver)
    - cups-devel
    - git
environment: |
    unset LD_AS_NEEDED
setup      : |
    %patch -p1 < $pkgfiles/sysroot.patch

    FLAGS=(`cat $pkgfiles/gn-build-config`)

    # Bootstrap GN with build config
    python tools/gn/bootstrap/bootstrap.py --gn-gen-args "${FLAGS[*]}"
build      : |
    ninja -C out/Release media/ffmpeg -v
install    : |
    install -Dm00644 out/Release/libffmpeg.so $installdir/%libdir%/libffmpeg.so
