name       : ffmpeg-chromium
version    : 80.0.3987.132
release    : 7
source     :
    - https://commondatastorage.googleapis.com/chromium-browser-official/chromium-80.0.3987.132.tar.xz : 2c0012059046a5a7e2bf6e9502f1898f1953226d63b724b82fc18226e285c201
license    :
    - BSD-3-Clause
    - LGPL-3.0-or-later
    - GPL-3.0-or-later
component  : multimedia.codecs
summary    : Chromium's ffmpeg for Chromium based browsers
description: |
    Chromium's ffmpeg for Chromium based browsers such as Opera and Vivaldi with support for proprietary codecs such as H.264 enabled.
clang      : yes
libsplit   : no
builddeps  :
    - pkgconfig(gtk+-x11-3.0)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(krb5-gssapi)
    - pkgconfig(lcms2)
    - pkgconfig(libjpeg)
    - pkgconfig(libpci)
    - pkgconfig(libpulse)
    - pkgconfig(libxslt)
    - pkgconfig(nss)
    - pkgconfig(xtst)
    - pkgconfig(xscrnsaver)
    - cups-devel
    - git
environment: |
    unset LD_AS_NEEDED
setup      : |
    FLAGS=(`cat $pkgfiles/gn-build-config`)

    # Bootstrap GN with build config
    python tools/gn/bootstrap/bootstrap.py --gn-gen-args "${FLAGS[*]}"
build      : |
    ninja -C out/Release media/ffmpeg -v
install    : |
    install -Dm00644 out/Release/libffmpeg.so $installdir/%libdir%/libffmpeg.so
