name       : ffmpeg-chromium
version    : 93.0.4577.63
release    : 11
source     :
    - https://commondatastorage.googleapis.com/chromium-browser-official/chromium-93.0.4577.62.tar.xz : 53462f58b8e77671d73fe7d22bcd5669740353a2d81af82b36b25bd456bc5852
license    :
    - BSD-3-Clause
    - LGPL-3.0-or-later
    - GPL-3.0-or-later
component  : multimedia.codecs
summary    : Chromium's ffmpeg for Chromium based browsers
description: |
    Chromium's ffmpeg for Chromium based browsers such as Opera and Vivaldi with support for proprietary codecs such as H.264 enabled.
clang      : yes
libsplit   : no
builddeps  :
    - pkgconfig(dri)
    - pkgconfig(gtk+-x11-3.0)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(krb5-gssapi)
    - pkgconfig(lcms2)
    - pkgconfig(libcurl)
    - pkgconfig(libdrm)
    - pkgconfig(libjpeg)
    - pkgconfig(libpci)
    - pkgconfig(libpulse)
    - pkgconfig(libva)
    - pkgconfig(libxslt)
    - pkgconfig(nss)
    - pkgconfig(xtst)
    - pkgconfig(xscrnsaver)
    - cups-devel
    - git
    - nodejs
environment: |
    unset LD_AS_NEEDED
setup      : |
    FLAGS=(`cat $pkgfiles/gn-build-config`)

    # Fix build with ffmpeg
    %patch -p1 < $pkgfiles/chromium-93-ffmpeg-4.4.patch

    # Revert ignorelist since it requires clang 13+
    %patch -Rp1 < $pkgfiles/replace-blacklist-with-ignorelist.patch

    # Various fixes
    %apply_patches

    # Bootstrap GN with build config
    python tools/gn/bootstrap/bootstrap.py --gn-gen-args "${FLAGS[*]}"

    # Fix missing tools
    mkdir -p third_party/node/linux/node-linux-x64/bin
    ln -s /usr/bin/node third_party/node/linux/node-linux-x64/bin/
build      : |
    ninja -C out/Release media/ffmpeg -v
install    : |
    install -Dm00644 out/Release/libffmpeg.so $installdir/%libdir%/libffmpeg.so
