name       : ffmpeg-chromium
version    : 94.0.4606.71
release    : 12
source     :
    - https://commondatastorage.googleapis.com/chromium-browser-official/chromium-94.0.4606.71.tar.xz : cabbba2e608c5ec110850b14ee5fead2608c44447a52edb80e2ba8261be3dc5b
license    :
    - BSD-3-Clause
    - LGPL-3.0-or-later
    - GPL-3.0-or-later
component  : multimedia.codecs
summary    : Chromium's ffmpeg for Chromium based browsers
description: |
    Chromium's ffmpeg for Chromium based browsers such as Opera and Vivaldi with support for proprietary codecs such as H.264 enabled.
clang      : yes
libsplit   : no
builddeps  :
    - pkgconfig(dri)
    - pkgconfig(gtk+-x11-3.0)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(krb5-gssapi)
    - pkgconfig(lcms2)
    - pkgconfig(libcurl)
    - pkgconfig(libdrm)
    - pkgconfig(libjpeg)
    - pkgconfig(libpci)
    - pkgconfig(libpulse)
    - pkgconfig(libva)
    - pkgconfig(libxslt)
    - pkgconfig(nss)
    - pkgconfig(xtst)
    - pkgconfig(xscrnsaver)
    - cups-devel
    - git
    - nodejs
environment: |
    unset LD_AS_NEEDED
setup      : |
    FLAGS=(`cat $pkgfiles/gn-build-config`)

    # Misc
    %patch -Np0 < $pkgfiles/unexpire-accelerated-video-decode-flag.patch

    # Revert ignorelist since it requires clang 13+
    %patch -Rp1 < $pkgfiles/replace-blacklist-with-ignorelist.patch

    # Revert use of -ffile-compilation-dir= since it requires clang 13+
    %patch -Rp1 < $pkgfiles/add-a-TODO-about-a-missing-pnacl-flag.patch
    %patch -Rp1 < $pkgfiles/use-ffile-compilation-dir.patch

    # Bootstrap GN with build config
    python tools/gn/bootstrap/bootstrap.py --gn-gen-args "${FLAGS[*]}"

    # Fix missing tools
    mkdir -p third_party/node/linux/node-linux-x64/bin
    ln -s /usr/bin/node third_party/node/linux/node-linux-x64/bin/
build      : |
    ninja -C out/Release media/ffmpeg -v
install    : |
    install -Dm00644 out/Release/libffmpeg.so $installdir/%libdir%/libffmpeg.so
